options(repos = c(CRAN = "http://cran.rstudio.com"))
install.packages("r-plyr")
install.packages("devtools")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("shiny")
install.packages("rmarkdown")
install.packages("forecast")
install.packages("stringr")
install.packages("rsqlite")
install.packages("reshape2")
install.packages("nycflights13")
install.packages("caret")
install.packages("rcurl")
install.packages("crayon")
install.packages("randomforest")
install.packages("xgboost")